### ISSUE TITLE
Could you please help me with "raise ValueError"?

### ISSUE THREAD

**Issue by AllenShow** [apolcyn/traclus_impl#3]
Traclus_impl can work well with the data set "raw_campus_trajectories.txt", but when I use my own data set, it returns "raise ValueError". I have tried with different data sets and each one's format is the same as   "raw_campus_trajectories.txt". So could you please help me?

An example of my data set:
{"epsilon":0.2,"min_neighbors":2,"min_num_trajectories_in_cluster":1,"min_vertical_lines":2,"min_prev_dist":0.2,"trajectories":[[{"x":77.5,"y":-47.5},{"x":82.5,"y":-47.5},{"x":77.5,"y":-47.5},{"x":72.5,"y":-47.5},{"x":77.5,"y":-47.5},{"x":72.5,"y":-47.5},{"x":82.5,"y":-47.5},{"x":82.5,"y":-52.5},{"x":77.5,"y":-52.5},{"x":77.5,"y":-47.5},{"x":72.5,"y":-47.5},{"x":67.5,"y":-47.5},{"x":67.5,"y":-52.5},{"x":67.5,"y":-57.5},{"x":72.5,"y":-57.5},{"x":72.5,"y":-62.5},{"x":67.5,"y":-62.5},{"x":72.5,"y":-62.5},{"x":67.5,"y":-62.5},{"x":67.5,"y":-57.5},{"x":72.5,"y":-57.5},{"x":172.5,"y":-117.5},{"x":167.5,"y":-117.5},{"x":167.5,"y":-112.5},{"x":167.5,"y":-107.5},{"x":162.5,"y":-102.5},{"x":162.5,"y":-107.5},{"x":157.5,"y":-107.5},{"x":157.5,"y":-102.5},{"x":152.5,"y":-102.5},{"x":147.5,"y":-102.5},{"x":142.5,"y":-102.5},{"x":137.5,"y":-102.5},{"x":132.5,"y":-102.5},{"x":132.5,"y":-97.5},{"x":127.5,"y":-97.5},{"x":132.5,"y":-97.5},{"x":132.5,"y":-102.5},{"x":137.5,"y":-102.5},{"x":142.5,"y":-107.5},{"x":137.5,"y":-107.5},{"x":132.5,"y":-107.5},{"x":137.5,"y":-107.5},{"x":132.5,"y":-107.5},{"x":127.5,"y":-107.5},{"x":127.5,"y":-102.5},{"x":122.5,"y":-102.5},{"x":117.5,"y":-102.5},{"x":112.5,"y":-102.5},{"x":72.5,"y":-47.5},{"x":72.5,"y":-52.5},{"x":77.5,"y":-57.5},{"x":77.5,"y":-52.5},{"x":77.5,"y":-57.5},{"x":72.5,"y":-52.5},{"x":72.5,"y":-57.5},{"x":72.5,"y":-52.5},{"x":72.5,"y":-47.5},{"x":72.5,"y":-52.5},{"x":67.5,"y":-52.5},{"x":67.5,"y":-47.5},{"x":67.5,"y":-52.5},{"x":72.5,"y":-52.5},{"x":72.5,"y":-57.5},{"x":67.5,"y":-57.5},{"x":67.5,"y":-62.5},{"x":72.5,"y":-62.5},{"x":72.5,"y":-67.5},{"x":72.5,"y":-72.5},{"x":72.5,"y":-77.5},{"x":77.5,"y":-77.5},{"x":77.5,"y":-82.5},{"x":77.5,"y":-87.5},{"x":72.5,"y":-87.5},{"x":62.5,"y":-97.5},{"x":62.5,"y":-92.5},{"x":67.5,"y":-92.5},{"x":72.5,"y":-92.5},{"x":77.5,"y":-92.5},{"x":212.5,"y":-117.5},{"x":217.5,"y":-117.5},{"x":217.5,"y":-112.5},{"x":222.5,"y":-112.5},{"x":227.5,"y":-112.5},{"x":232.5,"y":-112.5},{"x":237.5,"y":-112.5},{"x":237.5,"y":-117.5},{"x":237.5,"y":-112.5},{"x":232.5,"y":-112.5},{"x":227.5,"y":-107.5},{"x":222.5,"y":-107.5},{"x":222.5,"y":-102.5},{"x":222.5,"y":-97.5},{"x":217.5,"y":-97.5},{"x":217.5,"y":-92.5},{"x":217.5,"y":-87.5},{"x":217.5,"y":-92.5},{"x":217.5,"y":-87.5},{"x":217.5,"y":-82.5},{"x":217.5,"y":-77.5},{"x":217.5,"y":-72.5},{"x":222.5,"y":-72.5},{"x":217.5,"y":-72.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":222.5,"y":-62.5},{"x":222.5,"y":-67.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":227.5,"y":-62.5},{"x":232.5,"y":-62.5},{"x":227.5,"y":-62.5},{"x":227.5,"y":-57.5},{"x":222.5,"y":-57.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-57.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-67.5},{"x":222.5,"y":-67.5},{"x":222.5,"y":-62.5},{"x":222.5,"y":-67.5},{"x":217.5,"y":-67.5},{"x":222.5,"y":-67.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":222.5,"y":-67.5},{"x":217.5,"y":-62.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":212.5,"y":-62.5},{"x":217.5,"y":-57.5},{"x":217.5,"y":-62.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-57.5},{"x":217.5,"y":-52.5},{"x":217.5,"y":-47.5},{"x":217.5,"y":-52.5},{"x":217.5,"y":-57.5},{"x":222.5,"y":-57.5},{"x":227.5,"y":-57.5},{"x":222.5,"y":-57.5},{"x":222.5,"y":-52.5},{"x":222.5,"y":-57.5},{"x":227.5,"y":-57.5},{"x":222.5,"y":-62.5},{"x":217.5,"y":-62.5},{"x":217.5,"y":-57.5},{"x":222.5,"y":-57.5}]]}

I use it like this: python main.py -i ./input_json  -o ./traclus_output_test_json
And the error information is as follows:

Traceback (most recent call last):
  File "main.py", line 105, in <module>
    main()
  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 35, in main
    clusters_output_file_name) 
  File "main.py", line 72, in parse_input_and_run_traclus
    clusters_hook=clusters_hook)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 40, in run_traclus
    clusters_hook=clusters_hook)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 67, in the_whole_enchilada
    min_num_trajectories_in_cluster=min_num_trajectories_in_cluster)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 92, in representative_line_seg_iterable_from_all_points_iterable
    clusters = get_cluster_iterable_from_all_points_iterable_caller(point_iterable_list)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 75, in _func
    dbscan_caller=dbscan_caller)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 101, in get_cluster_iterable_from_all_points_iterable
    return dbscan_caller(get_all_traj_segs_from_all_points_caller(point_iterable_list))
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 112, in _func
    line_seg_from_points_func=line_seg_from_points_func)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 129, in get_all_trajectory_line_segments_iterable_from_all_points_iterable
    line_seg_from_points_func=line_seg_from_points_func)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 144, in get_trajectory_line_segments_from_points_iterable
    good_point_iterable = filter_by_indices(good_indices=trajectory_partitioning_func(trajectory_point_list=point_iterable), \
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 41, in call_partition_trajectory
    individual_line_seg_model_cost_computer=individual_line_seg_model_cost_computer)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 120, in partition_trajectory
    get_model_cost_computer_func(individual_line_seg_model_cost_computer))
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 98, in _func
    line_segment_creator=line_segment_creator)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 142, in partition_cost_computer
    model_cost = model_cost_computer(partition_line)
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 68, in _func
    total.increment(func(num))
  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 74, in individual_line_seg_model_cost_computer
    raise ValueError
ValueError

**Comment by apolcyn** [comment]
Hi allenshow,

The latest version 0.9.8 should fox this. When there are sequences of
points in the trajectories of the form like
.. (x1, y1), (x2, y2), (x1, y1) ...., that will happen. The latest version
removes those "spikes" in the input (0 distance between points that are one
point away from eachothet).

Thanks for letting me know, let me know if that doesn't work.

Alex

**Comment by apolcyn** [comment]
If removing points like that on the input messes things up, the partitioning could also be changed to just keep all of the points in those "loops". It just comes down to avoiding zero-length line segments...

**Comment by AllenShow** [comment]
Hi apolcyn,


I have updated traclus_impl to the latest version, but the error still happens.   The error information is as follows. I also attached my data set in this email. Could you please tell me how to do?





$ python main.py -i ./json  -o ./traclus_output_test_json1

/Users/ALLEN/GitHub/traclus_impl/traclus_impl/traclus_dbscan.pyc: rtree import succeeded. Using an r-tree for clusteringTraceback (most recent call last):

  File "main.py", line 105, in <module>

    main()

  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__

    return self.main(*args, **kwargs)

  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main

    rv = self.invoke(ctx)

  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "//anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke

    return callback(*args, **kwargs)

  File "main.py", line 35, in main

    clusters_output_file_name) 

  File "main.py", line 72, in parse_input_and_run_traclus

    clusters_hook=clusters_hook)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 39, in run_traclus

    clusters_hook=clusters_hook)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 81, in the_whole_enchilada

    min_num_trajectories_in_cluster=min_num_trajectories_in_cluster)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 106, in representative_line_seg_iterable_from_all_points_iterable

    clusters = get_cluster_iterable_from_all_points_iterable_caller(point_iterable_list)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 89, in _func

    dbscan_caller=dbscan_caller)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 115, in get_cluster_iterable_from_all_points_iterable

    return dbscan_caller(get_all_traj_segs_from_all_points_caller(point_iterable_list))

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 126, in _func

    line_seg_from_points_func=line_seg_from_points_func)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 143, in get_all_trajectory_line_segments_iterable_from_all_points_iterable

    line_seg_from_points_func=line_seg_from_points_func)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/coordination.py", line 158, in get_trajectory_line_segments_from_points_iterable

    good_point_iterable = filter_by_indices(good_indices=trajectory_partitioning_func(trajectory_point_list=point_iterable), \

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 41, in call_partition_trajectory

    individual_line_seg_model_cost_computer=individual_line_seg_model_cost_computer)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 122, in partition_trajectory

    get_model_cost_computer_func(individual_line_seg_model_cost_computer))

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 100, in _func

    line_segment_creator=line_segment_creator)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 144, in partition_cost_computer

    model_cost = model_cost_computer(partition_line)

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 68, in _func

    total.increment(func(num))

  File "/Users/ALLEN/GitHub/traclus_impl/traclus_impl/trajectory_partitioning.py", line 76, in individual_line_seg_model_cost_computer

    " a trajectory of the form [...(x1, y1), (x2, y2), (x1, y1)...]")

ValueError: line seg has zero length: start: x: 87.5. y: -92.5. end: x: 87.5. y: -92.5. Good chance there's a sequence of points in  a trajectory of the form [...(x1, y1), (x2, y2), (x1, y1)...]













At 2016-03-30 23:54:32, "apolcyn" <notifications@github.com> wrote:
Hi allenshow,

The latest version 0.9.8 should fox this. When there are sequences of
points in the trajectories of the form like
.. (x1, y1), (x2, y2), (x1, y1) ...., that will happen. The latest version
removes those "spikes" in the input (0 distance between points that are one
point away from eachothet).

Thanks for letting me know, let me know if that doesn't work.

Alex

**Comment by apolcyn** [comment]
It looks like at least some of those trajectories in that file go back and forth between the same points a lot. 
like here: {"x":87.5,"y":-92.5},{"x":92.5,"y":-92.5},{"x":97.5,"y":-92.5},{"x":92.5,"y":-92.5},{"x":97.5,"y":-92.5},{"x":102.5,"y":-92.5},{"x":97.5,"y":-92.5}
This exercises some funny edge cases in the partitioning cost computing code (e.g. lines that go back and forth, small loops).

There is a cleaning of input for this in run_traclus, but it hasn't been tested a lot.

Thanks for sharing, in the coming days I'll be revising the partitioning part anyways, and will hopefully fix this. For now I would see if you can first clean your input so that there aren't lots of the same points in each trajectory.

**Comment by apolcyn** [comment]
The latest version 0.999 I think should fix this. The partitioning phase should also run a lot faster now too. Let me know if there are more issues.
Thanks
